// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { getAuth } from 'firebase/auth';
import { Database } from './types';

const SUPABASE_URL = "https://ijbzmdaofhcppkhgrmbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqYnptZGFvZmhjcHBraGdybWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTg0OTEsImV4cCI6MjA1ODU3NDQ5MX0.AgmZaF9OTwzRF0Ya42NUTFA-rmQxeitAwksA_ChM0SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
